LONG_READ_DIR:
    none
SHORT_READ_DIR:
    none
ASSEMBLERS:
    flye
VIRAL_TOOLS:
    ASSEMBLY:
        virsorter
    READS:
        virsorter
GENOME_SIZE:
    6000000
ASSEMBLER_PARAMS:
    FLYE_PARAMS:
        "--plasmids"
    METAFLYE_PARAMS:
        "--plasmids"
RACON_ROUNDS:
    4
GUPPY_MODEL:
    r941_min_high_g360
GTDBTK_REF_DIR:
    /srv/db/gtdbtk/official/release95
BUSCO_REF_DIR:
    /srv/longreads/nanopore/busco
CHECKV_DB:
    /srv/db/checkv/checkv-db-v1.0
MAX_THREADS:
    8
MAX_MEMORY:
    100
REFERENCE_FILTER:
    /srv/projects/CF_phage/data/reference_genomes/GCF_000006765.1.fasta

REFERENCE_GENOMES_DIR:
    test_data/reference_genomes

REFERENCE_GENOMES_PARAMS:
    COVERM_PARAMS:
        example_ref_genome:
            multiple_genomes: True

VIBRANT:
    MIN_LENGTH: 1000
    DATABASE_DIR: /srv/db/vibrant/1.2.1/databases
SEEKER:
    MIN_LENGTH: 1000
VIRSORTER:
    DATABASE_DIR: /srv/db/virsorter2
    MIN_LENGTH: 1000
