LONG_READ_DIR:
    none
SHORT_READ_DIR:
    none
ASSEMBLERS:
    flye
GENOME_SIZE:
    6000000
ASSEMBLER_PARAMS:
    FLYE_PARAMS:
        "--plasmids"
    METAFLYE_PARAMS:
        "--plasmids"
RACON_ROUNDS:
    4
GUPPY_MODEL:
    r941_min_high_g360
GTDBTK_REF_DIR:
    /srv/db/gtdbtk/official/release95
BUSCO_REF_DIR:
    /srv/longreads/nanopore/busco
MAX_THREADS:
    8
MAX_MEMORY:
    100
REFERENCE_GENOMES_DIR:
    test_data/reference_genomes

REFERENCE_GENOMES_PARAMS:
    COVERM_PARAMS:
        example_ref_genome:
            multiple_genomes: True

VIRSORTER:
    DATABASE_DIR: /srv/db/virsorter2
    MIN_LENGTH: 2000
