LONG_READ_DIR:
    none
SHORT_READ_DIR:
    none
ASSEMBLERS:
    flye,canu
GENOME_SIZE:
    6000000
FLYE_PARAMS:
    ""
GUPPY_MODEL:
    r941_min_high_g360
GTDBTK_REF_DIR:
    /srv/db/gtdbtk/official/release95
BUSCO_REF_DIR:
    /srv/longreads/nanopore/busco
MAX_THREADS:
    8
MAX_MEMORY:
    100